export const STARTING_PREFIXES = [
  ...'abcdefghijklmnopqrstuvwxyz'.split(''),
  'ab', 'ac', 'ad', 'ag', 'al', 'am', 'an', 'ap', 'ar', 'as', 'at',
  'be', 'bi', 'bl', 'br',
  'ca', 'ch', 'cl', 'co', 'cr',
  'de', 'di', 'do', 'dr',
  'ea', 'el', 'en', 'ex',
  'fa', 'fi', 'fl', 'fo', 'fr',
  'ga', 'gl', 'go', 'gr',
  'he', 'hi', 'ho',
  'in', 'im', 'ir',
  'la', 'le', 'li', 'lo',
  'ma', 'me', 'mi', 'mo',
  'no',
  'pa', 'pe', 'pl', 'po', 'pr',
  'qu',
  're', 'ro',
  'sc', 'se', 'sh', 'si', 'sl', 'sm', 'sn', 'so', 'sp', 'st', 'str',
  'ta', 'te', 'th', 'to', 'tr',
  'un',
  'wa', 'wh', 'wo',
]

export const ENDING_SUFFIXES = [
  'a', 'e', 'i', 'o', 'y',
  'ad', 'ag', 'al', 'am', 'an', 'ar', 'as', 'at',
  'ck', 'de', 'ed', 'el', 'en', 'er', 'es', 'et',
  'ft', 'ge', 'gh', 'ht', 'ic', 'id', 'il', 'in', 'ip', 'it',
  'le', 'ly', 'me', 'nd', 'ne', 'ng', 'nt',
  'on', 'op', 'or', 'ot', 'ow',
  'se', 'sh', 'ss', 'st', 'te', 'th',
  'able', 'ally', 'ance', 'ence', 'ful', 'ing', 'ion', 'ish', 'ism',
  'ist', 'ity', 'less', 'ment', 'ness', 'ous', 'ship', 'tion',
]

export const CONTAINS_COMBINATIONS = [
  'aa', 'ae', 'ai', 'ao', 'au',
  'bb', 'bl', 'br',
  'cc', 'ch', 'ck', 'cl', 'cr',
  'dd', 'dr',
  'ea', 'ee', 'ei', 'eo', 'eu',
  'ff', 'fl', 'fr',
  'gg', 'gh', 'gl', 'gr',
  'ie', 'igh', 'ing',
  'll',
  'oo', 'ou', 'ow', 'oy',
  'ph', 'pl', 'pr',
  'qu',
  'sc', 'sh', 'sk', 'sl', 'sm', 'sn', 'sp', 'st', 'str',
  'th', 'tr',
  'wh', 'wr',
  'zz',
]